SUPABASE_URL = "https://dmirbjfwbvroefhyxvfs.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtaXJiamZ3YnZyb2VmaHl4dmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgzMzU5MDAsImV4cCI6MjEwMzkxMTkwMH0.MyMYlOZ-3eIL2-6jgYBleosoRRI6Fk3EPz3rJllwSKQ"
